version: '3.9'

services:      
  db:
    image: postgres:latest
    env_file:
      - ./env/db.dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ./env/pgadmin.dev.env
    ports:
      - 5555:80
    
  camunda:
    build: ./camunda
    ports: 
      - 8080:8080
    env_file:
      - ./env/camunda.dev.env
    depends_on:
      - db
    restart: always
    volumes:
      - ./conf/default.yml:/camunda/configuration/default.yml
      - ./conf/production.yml:/camunda/configuration/production.yml


volumes:
  postgres_data:
