# Get Camunda-run as base image
FROM camunda/camunda-bpm-platform:run-latest

# Copy the keycloak plugin to the configuration folder
COPY camunda-bpm-identity-keycloak-run-2.0.0.jar /camunda/configuration/userlib
